### ISSUE TITLE
Improve how the volume is changed

### ISSUE THREAD

**Issue by elamperti** [xstefanox/powermated#2]
I'll leave these observations/thoughts here, as I recently noticed there's a spike in CPU usage when I turn the knob a great amount or back and forth several times:
![selection_029](https://user-images.githubusercontent.com/910672/28400374-1031e094-6ce9-11e7-8bf5-af37395b1af8.jpg)
This is probably because each time the knob turns, powermated creates a subprocess to execute `amixer` and change the volume.

Even if the CPU impact is mild, another -indirect- consequence of this is that the volume sliders for left and right channels end up being unbalanced:
![selection_031](https://user-images.githubusercontent.com/910672/28400719-690d0c82-6ceb-11e7-8631-6d642bc1e9f9.jpg)
I believe this is some kind of race condition and it may be mitigated by either executing each process sequentially or by introducing a small delay between calls to `execute()`.

The actual solution would be to avoid creating subprocesses altogether by using signals or some other method (which at this moment I don't know), perhaps sending absolute values instead of small increments.

**Comment by xstefanox** [comment]
After a very long time, I finally took the time to solve this problem by transforming the events emitted by the device into PulseAudio commands.
This way, no process is forked at all and the execution is more efficient.

**Comment by elamperti** [comment]
Awesome, thank you! :smiley:
